import type { GetServerSideProps, NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Cards from "../components/cards";
import { Masonry } from "@mui/lab";
import { Badge, BadgeProps, Box, IconButton } from "@mui/material";
import { ShoppingCart } from "@mui/icons-material";
import { styled } from "@mui/material/styles";
import { useAppSelector } from "../hooks/redux";


interface Props {
  data: dataType[];
}

type dataType = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
};

const Home: NextPage<Props> = ({ data }) => {
  const item = useAppSelector((state) => state);

  const StyledBadge = styled(Badge)<BadgeProps>(({ theme }) => ({
    "& .MuiBadge-badge": {
      right: -3,
      top: 13,
      border: `2px solid ${theme.palette.background.paper}`,
      padding: "0 4px",
    },
  }));

  return (
    <div className="page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="buy">
        <Link href="/shop">
          <IconButton className="icon">
            <StyledBadge badgeContent={item.type} color="secondary">
              <ShoppingCart />
            </StyledBadge>
          </IconButton>
        </Link>
      </div>
      <Box width="95%" padding="10px">
        <Masonry columns={3} defaultColumns={3} spacing={3}>
          {data.map((e) => (
            <Cards key={e.id} {...e} />
          ))}
        </Masonry>
      </Box>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Fetch data from external API
  const res = await fetch(`https://fakestoreapi.com/products`);
  const data:Props[] = await res.json();

  // Pass data to the page via props
  //store.dispatch(increment());

  return { props: { data } };
};

export default Home;
